<?php defined('BASEPATH') or exit('No direct script access allowed');

if (!$CI->db->table_exists(db_prefix() . 'governments')) {
    $CI->db->query('CREATE TABLE `' . db_prefix() . "governments` (
      `userid` int(11) NOT NULL,
      `company` varchar(191) DEFAULT NULL,
      `perusahaan` varchar(191) DEFAULT NULL,
      `upt_id` int(11) DEFAULT NULL,
      `number_format` varchar(4) DEFAULT NULL,
      `prefix` varchar(10) DEFAULT NULL,
      `number` int(11) NOT NULL DEFAULT 0,
      `is_preffered` tinyint(1) NOT NULL DEFAULT 0,
      `vat` varchar(50) DEFAULT NULL,
      `phonenumber` varchar(30) DEFAULT NULL,
      `phone` varchar(30) DEFAULT NULL,
      `country` int(11) NOT NULL DEFAULT 0,
      `city` varchar(100) DEFAULT NULL,
      `zip` varchar(15) DEFAULT NULL,
      `state` varchar(50) DEFAULT NULL,
      `address` varchar(191) DEFAULT NULL,
      `website` varchar(150) DEFAULT NULL,
      `date` datetime NOT NULL DEFAULT current_timestamp(),
      `datecreated` datetime NOT NULL DEFAULT current_timestamp(),
      `dateactivated` datetime NOT NULL DEFAULT current_timestamp(),
      `last_status_change` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
      `active` int(11) NOT NULL DEFAULT 1,
      `status1` tinyint(1) DEFAULT NULL,
      `is_government` tinyint(1) NOT NULL DEFAULT 0,
      `is_institution` tinyint(1) NOT NULL DEFAULT 0,
      `is_inspector` tinyint(1) NOT NULL DEFAULT 0,
      `billing_street` varchar(200) DEFAULT NULL,
      `is_surveyor` tinyint(1) NOT NULL DEFAULT 0,
      `is_company` tinyint(1) DEFAULT 0,
      `institution_id` int(11) DEFAULT NULL,
      `head_id` int(11) DEFAULT NULL,
      `inspector_id` int(11) DEFAULT NULL,
      `inspector_staff_id` int(11) DEFAULT NULL,
      `bpjs_kesehatan` varchar(60) DEFAULT NULL,
      `bpjs_ketenagakerjaan` varchar(60) DEFAULT NULL,
      `siup` varchar(30) DEFAULT NULL,
      `hash` varchar(32) DEFAULT NULL,
      `addedfrom` int(11) NOT NULL DEFAULT 0,
      `isedit` tinyint(1) NOT NULL DEFAULT 0,
      `leadid` int(11) DEFAULT NULL,
      `billing_city` varchar(100) DEFAULT NULL,
      `billing_state` varchar(100) DEFAULT NULL,
      `billing_zip` varchar(100) DEFAULT NULL,
      `billing_country` int(11) DEFAULT 0,
      `shipping_street` varchar(200) DEFAULT NULL,
      `shipping_city` varchar(100) DEFAULT NULL,
      `shipping_state` varchar(100) DEFAULT NULL,
      `shipping_zip` varchar(100) DEFAULT NULL,
      `shipping_country` int(11) DEFAULT 0,
      `longitude` varchar(191) DEFAULT NULL,
      `latitude` varchar(191) DEFAULT NULL,
      `default_language` varchar(40) DEFAULT NULL,
      `default_currency` int(11) NOT NULL DEFAULT 0,
      `show_primary_contact` int(11) NOT NULL DEFAULT 0,
      `iis_perusahaan` tinyint(1) NOT NULL DEFAULT 0,
      `stripe_id` varchar(40) DEFAULT NULL,
      `registration_confirmed` int(11) NOT NULL DEFAULT 1
    ) ENGINE=InnoDB DEFAULT CHARSET=" . $CI->db->char_set . ';');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'governments`
      ADD PRIMARY KEY (`userid`),
      ADD UNIQUE KEY `prefix_number` (`prefix`,`number`) USING BTREE,
      ADD UNIQUE KEY `userid_institution_id` (`userid`,`institution_id`) USING BTREE,
      ADD UNIQUE KEY `company` (`company`) USING BTREE,
      ADD KEY `active` (`active`),
      ADD KEY `is_government` (`is_government`),
      ADD KEY `is_company` (`is_company`),
      ADD KEY `is_institution` (`is_institution`),
      ADD KEY `institution_id` (`institution_id`),
      ADD KEY `is_inspector` (`is_inspector`),
      ADD KEY `inspector_id` (`inspector_id`),
      ADD KEY `inspector_staff_id` (`inspector_staff_id`),
      ADD KEY `head_id` (`head_id`),
      ADD KEY `is_surveyor` (`is_surveyor`)
      ;');

    $CI->db->query('ALTER TABLE `' . db_prefix() . 'governments`
      MODIFY `userid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1');
}
